# Generated by Django 3.1.7 on 2021-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210330_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='such a place to be', max_length=255),
        ),
    ]
